spring:
  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
#    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost/db_springboot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform:


mensaje:
  hola: Hola desde thymeleaf

logging:
  level:
    org:
      hibernate:
        SQL : debug